In [5]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print("Array:", my_array)


Array: [1 2 3 4 5]


In [4]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print("Array:", my_array)
print("First element:", my_array[0])
print("Last element:", my_array[-1])

my_array_multiplied = my_array * 2
print("Array after multiplication by 2:", my_array_multiplied)


Array: [1 2 3 4 5]
First element: 1
Last element: 5
Array after multiplication by 2: [ 2  4  6  8 10]


In [3]:
import numpy as np
zeros = np.zeros(10)
ones = np.ones(10)
fives = np.full(10, 5)

print("Array of 10 zeros:", zeros)
print("Array of 10 ones:", ones)
print("Array of 10 fives:", fives)


Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]


In [2]:
import numpy as np

matrix = np.arange(2, 11).reshape(3, 3)
print("3x3 matrix with values ranging from 2 to 10:\n", matrix)


3x3 matrix with values ranging from 2 to 10:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
