In [2]:
def agecheck(age):
    if(age>=18):
        print("you can vote ")

    else:
        print("You can't vote ")

try:
    agecheck(15)

except ValueError as e:
    print(e)

You can't vote 


In [4]:
import numpy as np
i= ({10,30,25,45,78})
np.array=i
print(arr)

{30, 25, 10, 45, 78}


In [3]:
import numpy as np
arr = np.array({10,30,25,45,78})
print(arr)

{30, 25, 10, 45, 78}


In [1]:
import numpy as np

l=[10,30,25,45,78]
a=np.array(l)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])

print("array:",a)
print("array:",b)
print("array:",c)
print("array:",d)

print("array dimension",a.ndim)
print("array dimension",b.ndim)
print("array dimension",c.ndim)
print("array dimension",d.ndim)


#slicing array


arr=[10,20,30,4,5,6,7,8]
sarr=arr[1:5]
print(arr)
print(sarr)
arr[3]=100
print(arr)
print(sarr)

array: [10 30 25 45 78]
array: [1 2 3 4 5]
array: [[1 2 3]
 [4 5 6]]
array: [[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]
array dimension 1
array dimension 1
array dimension 2
array dimension 3
[10, 20, 30, 4, 5, 6, 7, 8]
[20, 30, 4, 5]
[10, 20, 30, 100, 5, 6, 7, 8]
[20, 30, 4, 5]


In [2]:
# The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array 
# will not affect the copy.
# The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original
# array will affect the view.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()

arr[0] = 42

print(arr)

print(x)



[42  2  3  4  5]
[1 2 3 4 5]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.view()

arr[0] = 42

print(arr)

print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [9]:
# numpy.zeros() in Python

# The numpy.zeros() function is one of the most significant functions which is used in machine learn programs widely. This function is used to generate an array containing zeros.

# The numpy.zeros() function provide a new array of given shape and type, which is filled with zeros.

# 1 numpy.zeros() without dtype and order 

import numpy as np

a=np.zeros(6)

a



array([0., 0., 0., 0., 0., 0.])

In [10]:
# 2: numpy.zeros() without order Import numpy as np

a=np.zeros((6,), dtype=int)

a



array([0, 0, 0, 0, 0, 0])

In [11]:
# 3 numpy.zeros() with shape Import numpy as np

a=np.zeros((6,2))

a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
# The NumPy ones() function in Python is used to create an array of the specified shape and type, where all the elements are set to 1. This function is very similar to zeros(). The ones() function takes three arguments and returns the array filled with value 1. In this article, I will explain how to use the NumPy ones() function with examples.



arr3=np.ones((5,2)) 
print(arr3)

arr = np.ones (7)



# Example 2: Create a 1D array of ones

# With 5 elements and integer data type 
arr =np.ones(5, dtype=int)

# Example 3: An aray with 6 ones and integer data type

arr = np.ones((6,), dtype=int)

# Example 4: Create two-dimensional array with ones

arr = np.ones((3, 4))

# Example 5: Use two-dimensional array with ones 
arr = (3,4)
# Example 6: use numpy.ones() where data type is float 
arr =np.ones([4, 3], dtype = int)

# Example 7: create array with heterogeneous data types 
arr = np.ones((3,2), dtype=[('x', 'int'), ('y', 'float')])

# The eye tool returns a 2-D array with 1's as the diagonal and O's elsewhere. The diagonal can be main, upper, or lower depending on the optional parameter k. A positive kis for the upper diagonal, a negative k is for the lower, and a 0k (default) is for the main diagonal.

arr4=np.eye(3) 
print(arr4) 
arr4=np.eye(3,4)

print(arr4)

arr5=np.diag((3,4,1,6))

print(arr5)

print(arr5.ndim)

print(arr5.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[3 0 0 0]
 [0 4 0 0]
 [0 0 1 0]
 [0 0 0 6]]
2
(4, 4)
