In [10]:
import numpy as n
# arr = np.array([[1,2,3],[4,5,6],[4,5,6]])
# print(np.diag(arr))
# print(np.diag(()))

print(n.diag(arr))

# randint() is an inbuilt function of the random module in Python3. The random module gives access to various useful functions one of them being able to generate random numbers, which is randint()

rand=n.random.randint(0,10,2)

print(rand)

# This function generates an array of specified shape and fills it with random samples from a uniform distribution over the interval [0, 1).

rand=n.random.rand(4)

print(rand)

rand=n.random.rand(2,3)

print(rand)

arr=n.random.randint(0, 100, 12)

print(arr)

[[29  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 85  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 53  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 89  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 31  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  9  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  8  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 48  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 82  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 60  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 17  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 96]]
[5 7]
[0.0733174  0.17964976 0.85484869 0.73936504]
[[0.39655795 0.5375691  0.1176313 ]
 [0.31916641 0.03746105 0.66206012]]
[84 42 85 10 74 25 24 55 65 61 93 34]


In [11]:
arr=n.random. randint (0,100,12)
print(arr)
arr=arr.reshape (4,3)
print (arr)
print ("Array values is ", arr [0] [1])
print ("Array values is ",arr [1] [0])
print(arr.shape)
arr=arr.reshape(-1,4)
print(arr)
arr=arr. reshape (2, -1)
print(arr)

[55 95 81 75 30 59 91 30 33 62 95 76]
[[55 95 81]
 [75 30 59]
 [91 30 33]
 [62 95 76]]
Array values is  95
Array values is  75
(4, 3)
[[55 95 81 75]
 [30 59 91 30]
 [33 62 95 76]]
[[55 95 81 75 30 59]
 [91 30 33 62 95 76]]


In [13]:
import numpy as n

ar=n.array([1,20,5,9,3,4,8,5,6,2,25, 2,2265,3,33,])

slicing=ar [4:9]

print("new slicing ", slicing)

print("new array ",ar)

print (type (slicing))

print (type (ar))

slicing[:]=0

print("old Slicing ", slicing)

print("old array ",ar)

new slicing  [3 4 8 5 6]
new array  [   1   20    5    9    3    4    8    5    6    2   25    2 2265    3
   33]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
old Slicing  [0 0 0 0 0]
old array  [   1   20    5    9    0    0    0    0    0    2   25    2 2265    3
   33]


In [14]:
import numpy as np
print(ar)
print(ar[ar%2!=0])

[   1   20    5    9    0    0    0    0    0    2   25    2 2265    3
   33]
[   1    5    9   25 2265    3   33]


In [15]:
import numpy as n
ar = n.arange(1,15)
print(ar)
print(ar[ar%2==0])
print(ar[ar%2!=0])
print(ar[ar>8])
ar[ar%2==0]=0
print(ar)
arr = n.arange(1,8)
print(arr+2)
print(arr*2)
print(arr**2)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]
[ 1  3  5  7  9 11 13]
[ 9 10 11 12 13 14]
[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0]
[3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14]
[ 1  4  9 16 25 36 49]


In [16]:
arr=n.array([10,20,30,25,6,2])
print(n.min(arr))
print(n.max(arr))
print(n.argmin(arr))
print(n.sqrt(arr))
print(n.sin(arr))
print(n.cos(arr))

2
30
5
[3.16227766 4.47213595 5.47722558 5.         2.44948974 1.41421356]
[-0.54402111  0.91294525 -0.98803162 -0.13235175 -0.2794155   0.90929743]
[-0.83907153  0.40808206  0.15425145  0.99120281  0.96017029 -0.41614684]


In [19]:
import numpy as n
n.random.seed(122)
mat = n.random.randint(1,21,9).reshape(3,3)
print(mat)
print(n.sum(mat))
print(n.cumsum(mat))
print(n.min(mat))
print(n.max(mat))
print("--------------")
print(n.sum(mat,axis=0))
print(n.min(mat,axis=1)) 
print(n.max(mat,axis=1))
print(n.cumsum(mat,axis=1))

[[16 11 13]
 [17 13 16]
 [ 3 16 11]]
116
[ 16  27  40  57  70  86  89 105 116]
3
17
--------------
[36 40 40]
[11 13  3]
[16 17 16]
[[16 27 40]
 [17 30 46]
 [ 3 19 30]]


In [21]:
import numpy as n
n. random. seed (122)
mat=n. random. randint (1, 21, 10)
print (mat)
n. random. shuffle (mat)
print (mat)
print (n. unique (mat, return_index=True, return_counts=True) )
print (n. unique (mat) . size)

[16 11 13 17 13 16  3 16 11 10]
[13 16 16 11 16 10 11 13 17  3]
(array([ 3, 10, 11, 13, 16, 17], dtype=int32), array([9, 5, 3, 0, 1, 8]), array([1, 1, 2, 2, 3, 1]))
6
