In [1]:
import numpy as np
arr = np.array([1,2,3,4,7,8])
#split the array into 3 equal size sub arrays
sub_arrays = np.split(arr,3)

#printing the sub array
for sub_arr in sub_arrays:
    print(sub_arr)


[1 2]
[3 4]
[7 8]


In [2]:
import numpy as np
arr = np.array([3,1,2,4,5])

sorted_arr = np.sort(arr)
print("sorted array (ascending) ",sorted_arr)

sorted_arr_desc =np.sort(arr[::-1])
print("sorted array (decensding): ", sorted_arr_desc)

sorted array (ascending)  [1 2 3 4 5]
sorted array (decensding):  [1 2 3 4 5]


In [3]:
import numpy as np
matrix = np.array([[3,1,2],[6,5,4]])
sorted_matrix= np.sort(matrix, axis=1)
print("Sorted matrix (ascending along rows): ")
print(sorted_matrix)

Sorted matrix (ascending along rows): 
[[1 2 3]
 [4 5 6]]


In [4]:
arr1 =np.array([[1,2],[5,6]])
arr2 =np.array([[3,4],[7,8]])
result = np.concatenate((arr1,arr2),axis=1)
print(result)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
arr1 =np.array([[1,2],[5,6]])
arr2 =np.array([[3,4],[7,8]])
result = np.hstack((arr1,arr2))
print(result)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
arr1 =np.array([[1,2],[5,6]])
arr2 =np.array([[3,4],[7,8]])
result = np.vstack((arr1,arr2))
print(result)

[[1 2]
 [5 6]
 [3 4]
 [7 8]]


In [9]:
import numpy as np
classB = np.array([70,80,85,95,100])
classB_mean = np.mean(classB)
print('class B score Average ', classB_mean) 

var = np.var(classB)
print('class B varience is  ', var)

std = np.std(classB)
print('class B standard deviation is ', std)


class B score Average  86.0
class B varience is   114.0
class B standard deviation is  10.677078252031311


In [10]:
import numpy as np

#Test scores of 30 students 
test_scores = np.array([65, 75, 80, 85, 90, 92, 94, 95, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138]) 
median = np.percentile(test_scores, 50) 
print("Median (50th Percentile):",median)

Median (50th Percentile): 109.0


In [12]:
scores = np.array([85,92,78,88,95,72,89])
np.save('Student_scores.npy', scores)
loaded_scores = np.load('student_scores.npy')

print("Original Scores: ",scores)
print("Loaded Scores: ",loaded_scores)

Original Scores:  [85 92 78 88 95 72 89]
Loaded Scores:  [85 92 78 88 95 72 89]


In [13]:
import numpy as np

# Input temperatures
temperatures = np.array([32.5, 34.2, 36.8, 29.3, 31.0, 38.7, 23.1, 18.5, 22.8, 37.2])

# Find indices of hot days and cold days
hot_days_indices = np.where(temperatures > 35)[0]
cold_days_indices = np.where(temperatures < 5)[0]

# Print the results
print("Hot Days:")
print("Day")
for i in hot_days_indices:
    print(i + 1)
print("Temperature (°C)")
for i in hot_days_indices:
    print(temperatures[i])

print("\nCold Days:")
print("Day")
for i in cold_days_indices:
    print(i + 1)
print("Temperature (°C)")
for i in cold_days_indices:
    print(temperatures[i])


Hot Days:
Day
3
6
10
Temperature (°C)
36.8
38.7
37.2

Cold Days:
Day
Temperature (°C)


In [14]:
import numpy as np

# Input monthly sales data
monthly_sales = np.array([120, 135, 145, 165, 180, 155, 168, 190, 205, 198, 210, 225])

# Split the data into quarters
Q1_sales = monthly_sales[0:3]
Q2_sales = monthly_sales[3:6]
Q3_sales = monthly_sales[6:9]
Q4_sales = monthly_sales[9:12]

# Print the quarterly sales
print("Quarter 1 Sales (in thousands of dollars):", Q1_sales)
print("Quarter 2 Sales (in thousands of dollars):", Q2_sales)
print("Quarter 3 Sales (in thousands of dollars):", Q3_sales)
print("Quarter 4 Sales (in thousands of dollars):", Q4_sales)


Quarter 1 Sales (in thousands of dollars): [120 135 145]
Quarter 2 Sales (in thousands of dollars): [165 180 155]
Quarter 3 Sales (in thousands of dollars): [168 190 205]
Quarter 4 Sales (in thousands of dollars): [198 210 225]
